# Project: gmacario/gmacario.github.io
# File: .circleci/config.yml
# vim: tabstop=2 shiftwidth=2 expanttab

version: 2
jobs:
  build:
    docker:
            - image: circleci/ruby:2.6-rc-stretch-browsers
    steps:
      - checkout
      - run: echo "Check dependencies"
      - run: cat /etc/os-release
      - run: ruby --version
      - run: gem --version
      - run: bundle install
      - run: ls -la
      - run: echo "Build pages"
      - run: bundle exec jekyll build
      - run: echo "Check pages"
      - run: ls -la _site/index.html

# EOF
